"""
Build static JSON data and copy the interactive experiment report website.

Author: Aritra Bal (ETP)
Date: 2026-09-10
"""

from __future__ import annotations

import argparse
import csv
from datetime import datetime, timezone
import json
from pathlib import Path
import pickle
import shutil
import tempfile
from typing import Any

import numpy as np
from omegaconf import OmegaConf
from sklearn.metrics import roc_auc_score, roc_curve

import helpers.utils as ut


SCHEMA_VERSION = 1
ROC_GRID = np.linspace(0.0, 1.0, 1001)
REPORT_SITE_DIR = Path(__file__).resolve().parent / "report_site"
FRONTEND_FILES = (
    Path("index.html"),
    Path("assets/app.js"),
    Path("assets/styles.css"),
)


def _notice(message: str, level: str = "warning") -> dict[str, str]:
    """Return one path-free notice for the report UI."""
    return {"level": level, "message": message}


def _load_pickle(path: Path) -> Any:
    """Load a pickle generated by this training repository."""
    with path.open("rb") as stream:
        return pickle.load(stream)


def _load_config(path: Path) -> dict[str, Any]:
    """Load a resolved YAML configuration as plain Python values."""
    cfg = OmegaConf.load(path)
    return OmegaConf.to_container(cfg, resolve=True, throw_on_missing=True)


def _finite_vector(values: Any, name: str) -> np.ndarray:
    """Convert a stored metric to a nonempty finite one-dimensional array."""
    array = np.asarray(values, dtype=float).reshape(-1)
    if not len(array) or not np.all(np.isfinite(array)):
        raise ValueError(f"{name} must be a nonempty finite array")
    return array


def _validation_points(path: Path) -> list[dict[str, float | int]]:
    """Read the validation AUC at epoch zero and after every trained epoch."""
    history = _load_pickle(path)
    if not isinstance(history, dict) or "auc" not in history:
        raise ValueError("history does not contain validation AUC values")
    aucs = _finite_vector(history["auc"], "validation AUC")
    if np.any((aucs < 0.0) | (aucs > 1.0)):
        raise ValueError("validation AUC values must lie between zero and one")
    return [
        {"epoch": epoch, "auc": float(auc)}
        for epoch, auc in enumerate(aucs)
    ]


def _epoch_time_points(path: Path) -> list[dict[str, float | int]]:
    """Read one row per completed training epoch from its epoch-times CSV."""
    with path.open(newline="", encoding="utf-8") as stream:
        return [
            {"epoch": int(row["epoch"]), "seconds": float(row["seconds"])}
            for row in csv.DictReader(stream)
        ]


def _training_metadata(path: Path) -> tuple[int | None, str | None]:
    """Read completion metadata from a certified trained-model payload."""
    payload = _load_pickle(path)
    if not isinstance(payload, dict) or not isinstance(payload.get("training"), dict):
        raise ValueError("trained model does not contain training metadata")
    training = payload["training"]
    completed = training.get("completed_epochs")
    if not isinstance(completed, int) or isinstance(completed, bool) or completed < 1:
        raise ValueError("completed epoch count is invalid")
    stop_reason = training.get("stop_reason")
    if not isinstance(stop_reason, str) or not stop_reason:
        raise ValueError("stop reason is invalid")
    return completed, stop_reason


def _score_histogram(
    scores: np.ndarray, labels: np.ndarray, is_logits: bool, bins: int = 30,
) -> dict[str, list[float]]:
    """Bin classifier scores (converted to probabilities if they are logits) into a
    signal/background density histogram."""
    if is_logits:
        scores = ut.sigmoid(scores)
    edges = np.histogram_bin_edges(scores, bins=bins)
    signal_density, _ = np.histogram(scores[labels == 1.0], bins=edges, density=True)
    background_density, _ = np.histogram(scores[labels == 0.0], bins=edges, density=True)
    return {
        "bin_edges": edges.tolist(),
        "signal_density": signal_density.tolist(),
        "background_density": background_density.tolist(),
    }


def _roc_data(
    path: Path, is_logits: bool,
) -> tuple[float, int, list[dict[str, float]], dict[str, list[float]]]:
    """Recompute AUC, ROC points, and a score histogram from saved labels and classifier
    scores. AUC and ROC are invariant to the logit-to-probability conversion, since it is
    monotonic; only the histogram is affected."""
    result = _load_pickle(path)
    if not isinstance(result, dict) or not {"scores", "labels"} <= result.keys():
        raise ValueError("evaluation result does not contain scores and labels")
    scores = _finite_vector(result["scores"], "scores")
    labels = _finite_vector(result["labels"], "labels")
    if len(scores) != len(labels):
        raise ValueError("score and label counts differ")
    if not set(np.unique(labels)).issubset({0.0, 1.0}) or len(np.unique(labels)) != 2:
        raise ValueError("labels must contain both binary classes")

    auc = float(roc_auc_score(labels, scores))
    fpr, tpr, _ = roc_curve(labels, scores)
    interpolated_tpr = np.interp(ROC_GRID, fpr, tpr)
    interpolated_tpr[0], interpolated_tpr[-1] = 0.0, 1.0
    points = [
        {"fpr": float(grid_value), "tpr": float(tpr_value)}
        for grid_value, tpr_value in zip(ROC_GRID, interpolated_tpr)
    ]
    histogram = _score_histogram(scores, labels, is_logits)
    return auc, len(labels), points, histogram


def _config_groups(cfg: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Select reportable settings and omit all filesystem locations."""
    analytic = cfg.get("shots") is not None and cfg.get("shots") <= 0
    data = {
        key: cfg.get(key)
        for key in (
            "signal", "background", "n_signal", "n_background",
            "n_signal_val", "n_background_val", "n_signal_test",
            "n_background_test", "flat", "norm_pt",
        )
        if key in cfg
    }
    totals = {
        "training_jets": ("n_signal", "n_background"),
        "validation_jets": ("n_signal_val", "n_background_val"),
        "inference_jets": ("n_signal_test", "n_background_test"),
    }
    for name, components in totals.items():
        if all(type(cfg.get(key)) is int for key in components):
            data[name] = sum(cfg[key] for key in components)
    return {
        "data": data,
        "model": {
            key: cfg.get(key)
            for key in (
                "wires", "num_layers", "circuit_type",
                "operations_per_qubit", "aux_weights",
            )
            if key in cfg
        },
        "optimization": {
            "optimizer": "Adam",
            **{
                key: cfg.get(key)
                for key in (
                    "loss", "batch_size", "epochs", "lr", "improv",
                    "min_epochs", "decay_rate", "decay_patience",
                )
                if key in cfg
            },
        },
        "execution": {
            "device": cfg.get("device_name"),
            "diff_method": cfg.get("diff_method"),
            "backend": cfg.get("backend"),
            "mode": "analytic" if analytic else "finite shots",
            "shots": None if analytic else cfg.get("shots"),
        },
    }


def _summarize_configs(
    configs: list[dict[str, Any]],
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Return shared settings and enumerate values that differ between runs."""
    if not configs:
        empty = {"data": {}, "model": {}, "optimization": {}, "execution": {}}
        return empty, {}
    grouped = [(_config_groups(cfg), cfg.get("random_seed")) for cfg in configs]
    summary: dict[str, Any] = {}
    variations: dict[str, Any] = {}
    for group_name in ("data", "model", "optimization", "execution"):
        summary[group_name] = {}
        keys = dict.fromkeys(
            key for groups, _ in grouped for key in groups[group_name]
        )
        for key in keys:
            values = [groups[group_name].get(key) for groups, _ in grouped]
            if all(value == values[0] for value in values[1:]):
                summary[group_name][key] = values[0]
                continue
            summary[group_name][key] = "Varies by run"
            variations.setdefault(group_name, {})[key] = [
                {"random_seed": random_seed, "value": value}
                for value, (_, random_seed) in zip(values, grouped)
            ]
    return summary, variations


def _aggregate_validation(
    runs: list[dict[str, Any]],
) -> list[dict[str, float | int]]:
    """Average validation AUCs only across the epoch range shared by all runs."""
    histories = [run["validation_auc"] for run in runs if run["validation_auc"]]
    if not histories:
        return []
    common_length = min(len(history) for history in histories)
    aucs = np.asarray([
        [point["auc"] for point in history[:common_length]]
        for history in histories
    ])
    return [
        {
            "epoch": epoch,
            "mean": float(np.mean(aucs[:, epoch])),
            "std": float(np.std(aucs[:, epoch])),
            "n": len(histories),
        }
        for epoch in range(common_length)
    ]


def _aggregate_epoch_time(runs: list[dict[str, Any]]) -> list[dict[str, float | int]]:
    """Average epoch times only across the epoch range shared by all runs."""
    histories = [run["epoch_times"] for run in runs if run["epoch_times"]]
    if not histories:
        return []
    common_length = min(len(history) for history in histories)
    seconds = np.asarray([
        [point["seconds"] for point in history[:common_length]]
        for history in histories
    ])
    return [
        {
            "epoch": histories[0][index]["epoch"],
            "mean": float(np.mean(seconds[:, index])),
            "std": float(np.std(seconds[:, index])),
            "n": len(histories),
        }
        for index in range(common_length)
    ]


def _aggregate_roc(runs: list[dict[str, Any]]) -> list[dict[str, float]]:
    """Average run ROC curves on the evaluation module's 1001-point grid."""
    curves = [run["roc_points"] for run in runs if run["roc_points"]]
    if not curves:
        return []
    tprs = np.asarray([[point["tpr"] for point in curve] for curve in curves])
    means = np.mean(tprs, axis=0)
    standard_deviations = np.std(tprs, axis=0)
    means[0], means[-1] = 0.0, 1.0
    return [
        {
            "fpr": float(fpr),
            "mean_tpr": float(mean),
            "std_tpr": float(std),
            "n": len(curves),
        }
        for fpr, mean, std in zip(ROC_GRID, means, standard_deviations)
    ]


def _wandb_run_id(run_dir: Path) -> str | None:
    """Read the saved W&B run identifier without assuming its project URL."""
    path = run_dir / "wandb_run_id.txt"
    if not path.is_file():
        return None
    run_id = path.read_text(encoding="utf-8").strip()
    if not run_id or not all(character.isalnum() or character in "-_" for character in run_id):
        raise ValueError("W&B run identifier is invalid")
    return run_id


def _run_report(run_dir: Path, result_dir: Path) -> tuple[dict[str, Any], dict[str, Any] | None]:
    """Build one run report while retaining every recoverable artifact failure."""
    random_seed = int(run_dir.name)
    notices: list[dict[str, str]] = []
    cfg = None
    validation_auc: list[dict[str, float | int]] = []
    completed_epochs = None
    stop_reason = None
    test_auc = None
    evaluation_jets = 0
    roc_points: list[dict[str, float]] = []
    score_histogram: dict[str, list[float]] | None = None
    wandb_run_id = None
    epoch_times: list[dict[str, float | int]] = []

    config_path = run_dir / "config.yaml"
    if config_path.is_file():
        try:
            cfg = _load_config(config_path)
            if str(cfg.get("seed")) != run_dir.parent.name:
                notices.append(_notice("Saved experiment identifier does not match its directory."))
            if cfg.get("random_seed") != random_seed:
                notices.append(_notice("Saved random seed does not match its directory."))
        except Exception:
            notices.append(_notice("Configuration is malformed."))
    else:
        notices.append(_notice("Missing configuration."))

    history_path = run_dir / "history.pickle"
    if history_path.is_file():
        try:
            validation_auc = _validation_points(history_path)
        except Exception:
            notices.append(_notice("Validation history is malformed."))
    else:
        notices.append(_notice("Missing validation history."))

    epoch_times_path = run_dir / "epoch_times.csv"
    if epoch_times_path.is_file():
        try:
            epoch_times = _epoch_time_points(epoch_times_path)
        except Exception:
            notices.append(_notice("Epoch timing data is malformed."))
    # Missing epoch_times.csv is not reported: it's an optional artifact that
    # runs saved before this feature existed will not have.

    model_path = run_dir / "trained_model.pickle"
    if model_path.is_file():
        try:
            completed_epochs, stop_reason = _training_metadata(model_path)
        except Exception:
            notices.append(_notice("Training metadata is malformed."))
    else:
        notices.append(_notice("Missing trained model."))

    result_path = result_dir / "test_results.pickle"
    if result_path.is_file():
        try:
            is_logits = isinstance(cfg, dict) and cfg.get("loss") == "BCE"
            test_auc, evaluation_jets, roc_points, score_histogram = _roc_data(result_path, is_logits)
        except Exception:
            notices.append(_notice("Evaluation result is malformed."))
    else:
        notices.append(_notice("Missing evaluation result."))

    try:
        wandb_run_id = _wandb_run_id(run_dir)
    except (OSError, ValueError) as error:
        notices.append(_notice(str(error)))

    if test_auc is not None and validation_auc and completed_epochs is not None and cfg is not None:
        status = "complete"
    elif test_auc is not None or validation_auc:
        status = "partial"
    else:
        status = "unavailable"
    return {
        "random_seed": random_seed,
        "status": status,
        "completed_epochs": completed_epochs,
        "stop_reason": stop_reason,
        "final_validation_auc": validation_auc[-1]["auc"] if validation_auc else None,
        "test_auc": test_auc,
        "evaluation_jets": evaluation_jets,
        "wandb_run_id": wandb_run_id,
        "notices": notices,
        "validation_auc": validation_auc,
        "roc_points": roc_points,
        "score_histogram": score_histogram,
        "epoch_times": epoch_times,
    }, cfg


def build_experiment(experiment_dir: Path, results_dir: Path) -> dict[str, Any]:
    """Build one experiment document from every numeric random-seed directory."""
    experiment_id = experiment_dir.name
    notices: list[dict[str, str]] = []
    run_directories = []
    for child in sorted(experiment_dir.iterdir(), key=lambda path: path.name):
        if child.is_dir() and child.name.isdecimal():
            run_directories.append(child)
        elif child.is_dir():
            notices.append(_notice(
                f"Ignored nonnumeric saved-run directory '{child.name}'.", "info",
            ))
    run_directories.sort(key=lambda path: (int(path.name), path.name))

    matching_results = results_dir / experiment_id
    if matching_results.is_dir():
        known_seeds = {path.name for path in run_directories}
        for child in sorted(matching_results.iterdir(), key=lambda path: path.name):
            if child.is_dir() and child.name.isdecimal() and child.name not in known_seeds:
                notices.append(_notice(f"Ignored evaluation for unknown random seed {child.name}."))
            elif child.is_dir() and not child.name.isdecimal():
                notices.append(_notice(
                    f"Ignored nonnumeric result directory '{child.name}'.", "info",
                ))
    else:
        notices.append(_notice("No evaluation directory exists for this experiment."))

    runs = []
    configs = []
    for run_dir in run_directories:
        run, cfg = _run_report(run_dir, matching_results / run_dir.name)
        runs.append(run)
        notices.extend(
            _notice(
                f"random_seed={run['random_seed']}: {notice['message']}",
                notice["level"],
            )
            for notice in run["notices"]
        )
        if cfg is not None:
            configs.append(cfg)

    successful_runs = [run for run in runs if run["test_auc"] is not None]
    aucs = np.asarray([run["test_auc"] for run in successful_runs], dtype=float)
    total_jets = sum(run["evaluation_jets"] for run in successful_runs)
    if runs and all(run["status"] == "complete" for run in runs):
        status = "complete"
    elif runs and (successful_runs or any(run["validation_auc"] for run in runs)):
        status = "partial"
    else:
        status = "unavailable"

    config, config_variations = _summarize_configs(configs)
    if config_variations:
        notices.append(_notice("Some configuration settings vary between runs."))
    validation_runs = [
        {"random_seed": run["random_seed"], "points": run["validation_auc"]}
        for run in runs if run["validation_auc"]
    ]
    epoch_time_runs = [
        {"random_seed": run["random_seed"], "points": run["epoch_times"]}
        for run in runs if run["epoch_times"]
    ]
    roc_runs = [
        {
            "random_seed": run["random_seed"],
            "auc": run["test_auc"],
            "points": run["roc_points"],
        }
        for run in successful_runs
    ]
    score_distribution_runs = [
        {"random_seed": run["random_seed"], **run["score_histogram"]}
        for run in successful_runs if run["score_histogram"]
    ]
    public_runs = [
        {
            key: value for key, value in run.items()
            if key not in {"validation_auc", "roc_points", "score_histogram", "epoch_times"}
        }
        for run in runs
    ]
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "experiment": {"id": experiment_id, "status": status},
        "summary": {
            "run_count": len(runs),
            "successful_runs": len(successful_runs),
            "total_jets": total_jets,
            "jets_per_run": (
                successful_runs[0]["evaluation_jets"]
                if successful_runs and len({run["evaluation_jets"] for run in successful_runs}) == 1
                else None
            ),
            "mean_auc": float(np.mean(aucs)) if len(aucs) else None,
            "std_auc": float(np.std(aucs)) if len(aucs) else None,
        },
        "validation": {
            "aggregate": _aggregate_validation(runs),
            "runs": validation_runs,
        },
        "roc": {
            "aggregate": _aggregate_roc(successful_runs),
            "runs": roc_runs,
        },
        "epoch_times": {
            "aggregate": _aggregate_epoch_time(runs),
            "runs": epoch_time_runs,
        },
        "score_distribution": {
            "runs": score_distribution_runs,
        },
        "runs": public_runs,
        "config": config,
        "config_variations": config_variations,
        "notices": notices,
    }


def _index_entry(report: dict[str, Any]) -> dict[str, Any]:
    """Reduce an experiment report to the fields shown on its index card."""
    summary = report["summary"]
    execution = report["config"]["execution"]
    optimization = report["config"]["optimization"]
    return {
        "id": report["experiment"]["id"],
        "status": report["experiment"]["status"],
        "run_count": summary["run_count"],
        "successful_runs": summary["successful_runs"],
        "total_jets": summary["total_jets"],
        "mean_auc": summary["mean_auc"],
        "std_auc": summary["std_auc"],
        "loss": optimization.get("loss"),
        "device": execution.get("device"),
        "mode": execution.get("mode"),
        "notices": report["notices"],
    }


def _write_json_atomic(path: Path, document: dict[str, Any]) -> None:
    """Replace one JSON document only after its complete serialization."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=path.parent, delete=False,
    ) as stream:
        temporary = Path(stream.name)
        json.dump(document, stream, indent=2, allow_nan=False)
        stream.write("\n")
    temporary.chmod(0o644)
    temporary.replace(path)


def _copy_frontend(source_dir: Path, output_dir: Path) -> None:
    """Copy the fixed frontend files into the publication directory."""
    missing = [str(path) for path in FRONTEND_FILES if not (source_dir / path).is_file()]
    if missing:
        raise FileNotFoundError("Missing report frontend file(s): " + ", ".join(missing))
    for relative_path in FRONTEND_FILES:
        destination = output_dir / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_dir / relative_path, destination)


def publish_reports(
    models_dir: Path,
    results_dir: Path,
    output_dir: Path,
    site_dir: Path = REPORT_SITE_DIR,
) -> dict[str, Any]:
    """Publish all numeric experiments and return the generated index document."""
    if not models_dir.is_dir():
        raise NotADirectoryError(f"Models directory does not exist: {models_dir}")
    _copy_frontend(site_dir, output_dir)
    experiments = []
    experiment_directories = [
        path for path in models_dir.iterdir()
        if path.is_dir() and path.name.isdecimal()
    ]
    experiment_directories.sort(
        key=lambda path: (int(path.name), path.name), reverse=True,
    )
    for experiment_dir in experiment_directories:
        report = build_experiment(experiment_dir, results_dir)
        _write_json_atomic(output_dir / "data" / f"{experiment_dir.name}.json", report)
        experiments.append(_index_entry(report))

    index = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "experiments": experiments,
    }
    _write_json_atomic(output_dir / "data" / "index.json", index)
    return index


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse report publication command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Publish static interactive reports from saved experiments.",
    )
    parser.add_argument("--models-dir", type=Path, required=True)
    parser.add_argument("--results-dir", type=Path, default=Path("results"))
    parser.add_argument("--output-dir", type=Path, required=True)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    """Run report publication from the command line."""
    args = parse_args(argv)
    index = publish_reports(
        args.models_dir.expanduser().resolve(),
        args.results_dir.expanduser().resolve(),
        args.output_dir.expanduser().resolve(),
    )
    print(f"Published {len(index['experiments'])} experiment report(s).")


if __name__ == "__main__":
    main()
