seed: 'base_jetclass'
train: true
wires: 4
trash_qubits: 3
shots: 2500
train_n: 5000
valid_n: 1000
batch_size: 100
epochs: 40
backend: 'autograd'
device_name: 'lightning.kokkos'
lr: 0.005
save: true
flat: true
evictable: false
separate_ancilla: true
resume: false
desc: 'Jetclass dataset, Using arbitrary 3D rotations, no reuploading,separate ancilla, pt normalized to jet pt, qcd sample flattened using jet pt'
norm_pt: true
substructure: false 
PFCand_selection_type: 'random' # this argument is only relevant if substructure = true
use_reuploading: false
loss: 'semiclassical'
save_dir: '/work/abal/qae_hep/saved_models/'
data_dir: '/ceph/abal/JetClass/'
dump: '/ceph/abal/QML/JetClass/dumps/' # only for testing
read_n: 2000 # only for testing
load: false # only for testing
scheme: 'min' # only for testing
log_wandb: true # only for testing